#!/bin/bash
#
# fetchmail        Starts fetchmail as daemon.
#
#
# chkconfig: 2345 99 10

# Source function library.
. /etc/init.d/functions

function print_fetchmail_conf()
{
    perl -Mesmith::templates -e 'print esmith::templates::processTemplate({TEMPLATE_PATH=>"fetchmailrc", OUTPUT_TYPE=>"string"});'
}

RETVAL=0

start() {
	[ -x /usr/bin/fetchmail ] || exit 5

	# Check if any account is active
	if ! print_fetchmail_conf | grep -s ^poll &>/dev/null; then
	    echo "No active fetchmail accounts. Exiting gracefully."
	    exit 0
	fi

	# Default configuration
	USER="fetchmail"
	SSL_OPTIONS=""
	AUTH_TYPE="password"
	INTERVAL="600"
	EXTRA_OPTIONS="--fastuidl 1"
	FETCHMAILHOME="/var/run/fetchmail"

	export FETCHMAILHOME

	# Source local configuration
	if [ -f /etc/sysconfig/fetchmail ] ; then
	    . /etc/sysconfig/fetchmail
	fi

 	echo -n $"Starting fetchmail: "

	print_fetchmail_conf | \
	    daemon --user $USER \
	    /usr/bin/fetchmail $SSL_OPTIONS --auth $AUTH_TYPE \
	    --syslog -f - -d $INTERVAL $EXTRA_OPTIONS

	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/fetchmail
	return $RETVAL
}	
stop() {
	echo -n $"Shutting down fetchmail: "
	killproc fetchmail
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/fetchmail
	return $RETVAL
}
restart() {
	stop
	start
}
case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	status fetchmail
	;;
  restart)
  	restart
	;;
  condrestart)
	[ -f /var/lock/subsys/fetchmail ] && restart || :
	;;
  sigusr1)
        echo -n $"Waking up fetchmail: "
	killproc fetchmail -10
        RETVAL=$?
        echo
        exit $RETVAL
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|sigusr1}"
	exit 2
esac

exit $?

