#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-fetchmail-update event
#--------------------------------------------------

$event = "nethserver-fetchmail-update";
templates2events("/etc/sysconfig/fetchmail", $event);
templates2events("/etc/sudoers", $event);
event_services($event, qw(
   fetchmail restart
   rsyslog restart
));
event_actions($event, 'initialize-default-databases' => '00');

#--------------------------------------------------
# actions for nethserver-fetchmail-save event
#--------------------------------------------------
$event = "nethserver-fetchmail-save";
event_services($event, 'fetchmail' => 'restart');

#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event, 'nethserver-fetchmail-migrate' => 70);

#
# Whenever mail addresses change, restart fetchmail:
#
event_actions($_, qw(
    nethserver-fetchmail-condrestart 95
)) foreach(qw(
    user-modify
    user-delete
    group-modify
    group-delete
));
