#!/usr/bin/perl

use esmith::DB::db;
use esmith::event;
use File::Copy;
use strict;

my $event = shift;
my $sourceDir = shift;
my $esmithDbDir = '/home/e-smith/db';
my $errors = 0;
if( ! -d $sourceDir) {
    die("Could not find dir $sourceDir");
}

my $srcConfigDb = esmith::DB::db->open_ro(join('', $sourceDir, $esmithDbDir, '/configuration')) || die("Could not open source configuration database in $sourceDir \n");
my $dstConfigDb = esmith::DB::db->open('configuration') || die("Could not open destination account db\n");

my $service = 'fetchmail';
my $old = $srcConfigDb->get($service);

if (defined($old)) {
    my $new = $dstConfigDb->get($service) || $dstConfigDb->new_record($service, 'type' => 'service');
    $new->set_prop('externalFreq', '15');
    my $status = $old->prop('status') || 'disabled';
    $new->set_prop('status',$status); 

    copy(join('', $sourceDir, $esmithDbDir, '/fetchmail'), '/var/lib/nethserver/db/fetchmail');
    my $accountsdb = esmith::DB::db->open('fetchmail') || die("Could not open fetchmail database \n");
    foreach my $account ($accountsdb->get_all()) {
        $account->set_prop('proto','pop3');
    }

}

# Apply configuration
if( ! esmith::event::event_signal('nethserver-fetchmail-update')) {
    exit(1);
}
exit 0;
