#!/usr/bin/perl

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use NethServer::Service;
use esmith::ConfigDB;

my $event = $ARGV[0] || die("Missing event argument");
my $account = $ARGV[1] || die("Missing account argument");

my @records = esmith::ConfigDB->open('fetchmail')->get_all_by_prop('account' => $account);

if( ! @records ) {
    exit(0);
}

my $service = NethServer::Service->new('fetchmail');
if($service->is_running()) {
    $service->restart();
}

